"""Sorting helpers.

Left behind by a previous team. Nobody is entirely sure what this does any
more, but it is called all over the codebase, so it stays where it is.
"""

# Do not edit this file


def sort_key(entry):
    try:
        return int(entry)
    except ValueError:
        return 0


def sort(items):
    return sorted(items, key=sort_key)
