name: python_inside_out_tdd

services:
  exercises:
    build: .
    entrypoint:
      - /bin/sh
    volumes:
      - ./:/inside_out_tdd
      - python_inside_out_pytest_cache:/inside_out_tdd/.pytest_cache
      - python_inside_out_src_pycache:/inside_out_tdd/src/__pycache__
      - python_inside_out_tests_pycache:/inside_out_tdd/tests/__pycache__
    working_dir: /inside_out_tdd
    tty: true
    command:
      - -c
      - |
        echo 'export PS1="🐳 \033[1;32m\u@\033[1;34m\w\033[0m \$ "' >> /root/.profile
        echo 'trap "echo ‼️ You just quit the exercises terminal.; echo To get it back run: docker compose run exercises" EXIT' >> /root/.profile
        echo "To run the tests:"
        echo "  pytest -q"
        echo "Or for watch mode:"
        echo "  ptw -- -q"
        exec /bin/sh -l

volumes:
  python_inside_out_pytest_cache:
  python_inside_out_src_pycache:
  python_inside_out_tests_pycache:
