x-exercise: &exercise
  build:
    context: .
  entrypoint: /bin/sh

services:
  sync:
    image: "ghcr.io/skiller-whale/learnersync:0.2.1"
    network_mode: "host"
    environment:
      SERVER_URL: "https://train.skillerwhale.com/"
      SW_RUNNING_IN_HOSTED_ENV:
      WATCHER_BASE_PATH: "/exercises"
      ATTENDANCE_ID_FILE: "/attendance_id"
      WATCHED_EXTS: ".py"
      IGNORE_MATCH: ".git"
    volumes:
      - ./exercises:/exercises:ro
      - ./attendance_id:/attendance_id:ro
    tty: true
    stdin_open: true

  introduction_to_tdd:
    <<: *exercise
    volumes:
      - ./exercises/introduction_to_tdd:/introduction_to_tdd
    working_dir: /introduction_to_tdd
    environment:
      - PYTHONPATH=/introduction_to_tdd

  specifying_behaviour:
    <<: *exercise
    volumes:
      - ./exercises/specifying_behaviour:/specifying_behaviour
    working_dir: /specifying_behaviour
    environment:
      - PYTHONPATH=/specifying_behaviour

  failing_well:
    <<: *exercise
    volumes:
      - ./exercises/failing_well:/failing_well
    working_dir: /failing_well
    environment:
      - PYTHONPATH=/failing_well
